### ISSUE TITLE
unable to download d2_tf.pth

### ISSUE THREAD

**Issue by xiaoyugit111** [mihaidusmanu/d2-net#102]
someone got this please please tell me how
i could only find it 404 notfound

**Comment by xiaoyugit111** [comment]
problem solved.

**Comment by NaNtaisuike** [comment]
hello,i also can not download it, could you tell me how do you solve it please?

**Comment by mihaidusmanu** [comment]
Pleas try the following link https://dusmanu.com/files/d2-net/d2_tf.pth
