### ISSUE TITLE
Unable to download weight files!

### ISSUE THREAD

**Issue by ChengLiu-xsy** [mihaidusmanu/d2-net#104]
hello:
     When I download the weight file, it shows that I cannot access this website, can you re-upload the previous weight file.

**Comment by mihaidusmanu** [comment]
Hello, you can try the following link https://dusmanu.com/files/d2-net/d2_tf.pth

Updating dsmn.ml to dusmanu.com should make all links work again (will fix it in the following days)

**Comment by mihaidusmanu** [comment]
Readme updated > all links should work now!
