### ISSUE TITLE
D2Net model weights

### ISSUE THREAD

**Issue by sfm-user-1** [mihaidusmanu/d2-net#105]
Hi Mihai, I noticed that the website link with the D2Net model weights went down:  https://dsmn.ml/files/d2-net/d2_tf.pth

Would it be possible to restart the website or upload to another link? This is the link I see from the [readme]( https://dsmn.ml/files/d2-net/d2_tf.pth). Thank you!

**Comment by mihaidusmanu** [comment]
Hello. I already updated the readme last week pointing to dusmanu.com instead of dsmn.ml. Let me know if you find any reference to the old website.

**Comment by sfm-user-1** [comment]
Thank you Mihai.

**Comment by ParaImage** [comment]
Updated links not work.
