### ISSUE TITLE
unable to resolve host address ‘dsmn.ml’

### ISSUE THREAD

**Issue by NaNtaisuike** [mihaidusmanu/d2-net#107]
unable to resolve host address ‘dsmn.ml’
hello, when i want to download the models, wget have the erroe,

**Comment by mihaidusmanu** [comment]
All links were recently updated to the new website (dusmanu.com), e.g.:
`wget https://dusmanu.com/files/d2-net/d2_tf.pth -O models/d2_tf.pth`

**Comment by NaNtaisuike** [comment]
thanks so much! I have an another problem, why the function self.detection of D2Net model in train.py and extract_features.py are different, why do you do it so? thank you

**Comment by NaNtaisuike** [comment]
I know it! thank you so much!
