### ISSUE TITLE
The link to "d2-net/hpatches-sequences-cache" seems broken.

### ISSUE THREAD

**Issue by Ma0zii** [mihaidusmanu/d2-net#108]
Hello!! Thanks for your share. And I want to run bash download_cache.sh. But the link to "https://dsmn.ml/files/d2-net/hpatches-sequences-cache.tar.gz" seems broken. Can you share the new link please?

**Comment by mihaidusmanu** [comment]
Fixed in the latest commit. The link was moved to dusmanu.com

**Comment by Ma0zii** [comment]
> 已在最新提交中修复。链接已移至 dusmanu.com

Thank you very much. May you happy!! : )
