### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by XuyangBai** [mihaidusmanu/d2-net#12]
Hi, Thanks for your sharing. I wonder could you please share a tensorflow version of D2-Net ?

**Comment by mihaidusmanu** [comment]
Hello. I do not plan on releasing the TensorFlow version of the code - it is extremely outdated (it doesn't support the current dataset format so the training wouldn't work, it doesn't support batches, it doesn't do descriptor interpolation, etc) so the performance would be significantly impacted. Moreover, I have stopped using TF almost one year ago so it would probably take me a significant amount of time to fix it. Sorry for the inconvenience.
