### ISSUE TITLE
Overlap matrix resulting in many -1.

### ISSUE THREAD

**Issue by tonyngjichun** [mihaidusmanu/d2-net#15]
In ``megadepth_utils/preprocess_scene.py`` line 209, the inner loop's scope is defined as ``for idx2 in range(idx1 + 1, n_images):``.
This results in the lower triangle of the overlap matrix being all -1, hence drastically reducing the number of positive pairs. Could you confirm this is the case? Thanks

**Comment by mihaidusmanu** [comment]
Even though the for only loops over the upper triangle, the lower triangle is also filled - see lines  219-220 of the same file.

https://github.com/mihaidusmanu/d2-net/blob/be09ec72566968dfce96de577c5880a7aafdeace/megadepth_utils/preprocess_scene.py#L219-L220

**Comment by tonyngjichun** [comment]
Hi,

didn't notice this, thanks! gonna close the issue.
