### ISSUE TITLE
Data download error

### ISSUE THREAD

**Issue by edgar-explorer** [mihaidusmanu/d2-net#17]
Thank you for your good work. When I tried to download MegaDepth v1 Dataset for many times, but the data bag is very big ((ar.gz, 199 GB). Do you have another address to download this data part by part? Thank you.

**Comment by mihaidusmanu** [comment]
Hello. Sadly, I don't have an alternate download link for the MegaDepth data. I suggest using `wget` with the `--continue` (or `-c`) parameter to resume a failed download. You can also change the number of times wget retries the connection in case of an interruption using the `--tries` parameter (e.g. `--tries=1000`).

**Comment by edgar-explorer** [comment]
Thank you for your help.
