### ISSUE TITLE
MegaDepth

### ISSUE THREAD

**Issue by gentle-li** [mihaidusmanu/d2-net#18]
Hi,I have already downloaded MegaDepth dataset, still need to download sfm model? this is too big, except download sfm, is there a good way? thanks

**Comment by mihaidusmanu** [comment]
Hello. As mentioned in the README, please contact me by e-mail for access to the processed dataset (~250GB download).

**Comment by gentle-li** [comment]
> Hello. As mentioned in the README, please contact me by e-mail for access to the processed dataset (~250GB download).

sorry, i could't find your e-mail..

**Comment by mihaidusmanu** [comment]
Please find it at the following address: http://people.inf.ethz.ch/dusmanum/. I am waiting for you email.
