### ISSUE TITLE
Problem extracting multi-scale features

### ISSUE THREAD

**Issue by etrulls** [mihaidusmanu/d2-net#22]
It crashes [here](https://github.com/mihaidusmanu/d2-net/blob/cc519c12c53e4b3a97afc8f5e3303ee08356a309/lib/pyramid.py#L46), when operating on a byte() tensor and a boolean tensor. Works if you convert detections to .byte(). It was working the last time I tried, it could be a problem with library versions? I'm on torch 1.2.0 now. FYI.

**Comment by mihaidusmanu** [comment]
Thanks a lot for bringing this to my attention. I'm still on PyTorch 1.1 personally, but I'll upgrade and release a fix shortly.

**Comment by mihaidusmanu** [comment]
Fixed in the latest commit - PyTorch 1.2 introduced boolean tensors so VRAM usage should also be slightly lower now. Sorry for the delay.

**Comment by etrulls** [comment]
Pretty fast IMO, thanks. :)
