### ISSUE TITLE
About the localization benchmark

### ISSUE THREAD

**Issue by shamangary** [mihaidusmanu/d2-net#23]
Hi. I see the results on the localization benchmark for robotcar and cmu. Trying to reproduce the results. Here are some questions. 1) For colmap image_registrator, do you use incremental mapper such as bundle adjustment? Are there any special parameters you choose? Do you adopt extra global bundle adjustment as well (bundle_adjuster in colmap)? 2) It says that only the rear images are used. Does it mean only the dataset rear image are used as candidates? And why?

Thank you very much.

**Comment by tsattler** [comment]
1) No incremental mapping is used. Only the functionality readily provided by colmap image_registrator, which adds images to a model without adding point observations or bundle adjustment of the structure. We modified the parameters such that poses with fewer inliers than the standard parameters are accepted.
2) Yes, we only use the dataset rear images for query. Only these images are used by the evaluation server. Using the left and right images could further improve performance though (see the original paper).

**Comment by shamangary** [comment]
Thank you @tsattler. Is there a chance that this part of the experiment will be released soon?

**Comment by tsattler** [comment]
@shamangary All the code needed to replicate this experiment (D2-Net, [code for matching D2-Net features and importing them to colmap](https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation), colmap) is already available. We are currently not planning to release more code.

**Comment by shamangary** [comment]
Thanks
