### ISSUE TITLE
D2-Net feature matching

### ISSUE THREAD

**Issue by VPRzhou** [mihaidusmanu/d2-net#27]
Hi,can you show me a demo about the D2-Net feature match.For I want compare it with other features and demonstrate the robustness of D2-Net in varying conditions.
Another question I want to ask you.If I want to compare your method to some other methods,such as DELF、LF-Net、SuperPoint and so on.How can I do the process of evalution of their performance on changing environments and draw a curve in the coordinate axis,what is the definition of X axis and Y axis?
Looking forward your reply,thank you.

**Comment by tsattler** [comment]
There is a demo for D2-Net extraction and matching in the `qualitative` subfolder.
The definition of the x- and y-axes depends on what and how you are evaluating the features.

**Comment by VPRzhou** [comment]
thanks your reply. I want make a PR curve of these features when they are used to do Visual Place Recognition problems.Could you show me a demo about it

**Comment by tsattler** [comment]
I would recommend to first define how you measure precision and recall. Once you have these definitions, it should be fairly straight-forward to make the corresponding measurements and do the plots. 

There is a demo for the feature matching evaluation plots we did for the D2-Net paper in the repository. Hope that helps.

**Comment by VPRzhou** [comment]
Thank you for your reply. I have reproduce the feature matching evaluation plots in the D2-Net paper. But I have a question about the definition about X axis "threshold[px]" .I can not understand what it means. 
Another question, how can I use the D2-Net features represented by BoW to solve the loop closure detection problems. 
Looking forward your reply,thank you.

**Comment by tsattler** [comment]
Regarding the definition of the x-axis, you can find the definition in the D2-Net paper.

It should be fairly simple to integrate D2-Net features into existing BoW representations. But I am not familiar with them, so I cannot provide help here.
