### ISSUE TITLE
An error occurred when extracting multiscale features

### ISSUE THREAD

**Issue by stx024** [mihaidusmanu/d2-net#29]
When I try to extract multiscale features, an error occurred like this:

**Traceback (most recent call last):
  File "extract_features.py", line 120, in <module>
    model
  File "/data1/stx/D2-net/d2-net-master/lib/pyramid.py", line 46, in process_multiscale
    detections = torch.min(detections, (1 - banned))
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_min**

My python version is 3.6.6, pytorch version is 1.3.0

**Comment by mihaidusmanu** [comment]
You are not using the latest version of the D2-Net code. This was fixed in the latest commit. Make sure to pull before running the feature extraction again. Leaving this issue open in the meanwhile.

**Comment by stx024** [comment]
Thank you very much!

> You are not using the latest version of the D2-Net code. This was fixed in the latest commit. Make sure to pull before running the feature extraction again. Leaving this issue open in the meanwhile.

Thank you very much!

**Comment by stx024** [comment]
> You are not using the latest version of the D2-Net code. This was fixed in the latest commit. Make sure to pull before running the feature extraction again. Leaving this issue open in the meanwhile.

Thank you very much!
