### ISSUE TITLE
The different between SoftDetectionModule and HardDetectionModule

### ISSUE THREAD

**Issue by ahong007007** [mihaidusmanu/d2-net#31]
The training phase in the open source code uses the SoftDetectionModule in model.py. The test uses the HardDetectionModule of model_test.py. What is the difference?
Thanks.

**Comment by mihaidusmanu** [comment]
See section 3.2 of the paper - https://arxiv.org/pdf/1905.03561.pdf, paragraphs "Hard Feature Detection" and "Soft Feature Detection" respectively.

TL;DR: the soft feature detection is a soft translation of the hard feature detection using convolutional soft-max; the soft formulation is only used at train time.
