### ISSUE TITLE
How can I achieve acceleration in the feature matching phase?

### ISSUE THREAD

**Issue by ahong007007** [mihaidusmanu/d2-net#33]
The feature extraction phase can be based on GPU acceleration. How can I achieve acceleration in the feature matching phase?
Thank you!

**Comment by mihaidusmanu** [comment]
The link posted by @tsattler in your issue regarding 3D reconstruction actually integrates a GPU matcher as well: https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/matchers.py.
