### ISSUE TITLE
Test Network Arch.

### ISSUE THREAD

**Issue by PatrickRowsomeMovidius** [mihaidusmanu/d2-net#34]
Hi, 

Thanks for publishing your work, it is very interesting to review.

One question I have is about the testing time network configuration. In section 4.3 in the paper you mention a number of changes for the network for testing. Specifically, 
- replace pool3 with an average pooling layer with stride 1.
- Conv4_1 -> Conv4_3 is replaced with dilated convolutions with a rate of two.
In your code I was following the extract_features.py script which uses the D2Net model and as far as I understand this is configured differently, i.e. the truncated VGG16 net for the dense portion. It would be great if you could clarify this for me.

Kind Regards,
Patrick

**Comment by mihaidusmanu** [comment]
Hello. `extract_features.py` uses `model_test.py` (instead of `model.py`) which implements the architecture changes described in the paper, as you can see below:
https://github.com/mihaidusmanu/d2-net/blob/e8da4d0533cf8427ad566f69486d14880f6fac5c/lib/model_test.py#L10-L33

**Comment by PatrickRowsomeMovidius** [comment]
This makes sense, GitHubs new indexing is what confused me.

Thanks
