### ISSUE TITLE
Setting --preprocessing image for training and testing phase

### ISSUE THREAD

**Issue by GabbySuwichaya** [mihaidusmanu/d2-net#37]
Thanks for this great work! It all been doing so well. 
At the moment,  I have tried to tune the weights of the d2-net downloaded from https://github.com/mihaidusmanu/d2-net#downloading-the-models. 

I wonder which image preprocessing (caffe / torch ) option I should use for training and then testing ? 

I am confused because it seems that originally the modeled provided from https://github.com/mihaidusmanu/d2-net#downloading-the-models were trained using "Caffe". 
So, from my understanding, if I were to use the provided model directly, I should set the image proprocessing to "Caffe". Is that right?  
 
However, when it comes to tuning the model. 
I tuned them in Pytorch, but does this mean that I should use "torch"  (rather than caffe)  in my training ?
Then, as I want to also test this model, I have to set the preprocessing as torch ... Is this right?

**Comment by mihaidusmanu** [comment]
There are two things that need to be taken into account when setting the preprocessing flag:

1. At training, you need to use the same preprocessing as that of the ImageNet weights that you are trying to fine-tune (by default, `caffe`).

2. At test time, you need to use the same preprocessing as at train time (by default, `caffe` again).

In case you didn't modify the starting weights for training (i.e. you are using the default version of the script which loads the weights from `d2_ots.pth`), then you should stick to `caffe` preprocessing.

**Comment by GabbySuwichaya** [comment]
I see. Thanks for quick reply.  So, does this mean that only if  the pytorch VGG is used as the starting weight, i.e., vgg16 = models.vgg16(pretrained=True), then I might need to change the preprocessing to "torch" when training and testing ? Is that right?  Do they give a similar performance?

**Comment by mihaidusmanu** [comment]
Yes, if you set `pretrained=True` and comment line 117 from `train.py` (see below), then you need to use `torch` preprocessing. At least for the off-the-shelf models, the `caffe` weights give better performance - I don't remember exactly how the performance was after training.

https://github.com/mihaidusmanu/d2-net/blob/81983664d1a29fabf09636b3735c5df9151db600/train.py#L117

**Comment by GabbySuwichaya** [comment]
I see. Thanks so much, Will give it a try.

**Comment by GabbySuwichaya** [comment]
Thanks... It actually works too but the performance is not as competitive as the Caffe.  Nevertheless, do you  have any release for the tensor flow version of the D2-Net?

**Comment by mihaidusmanu** [comment]
Sadly, the TensorFlow + Keras code is very outdated (dating more than a year back) and I won't bother to update it: it doesn't support the current dataset format, batch sizes > 1, descriptor interpolation, etc. There are no plans to release it.

**Comment by GabbySuwichaya** [comment]
Thanks for your quick reply. I think I should close this issue.
