### ISSUE TITLE
Download problem（Undistorted_sfm）

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#38]
Hi mihaidusmanu,
When I downloaded Undistorted_SfM from Google  drive,only some files are automatically compressed for download, and then do I need to download the *.tar.gz one by one.How can I download all at once?

**Comment by mihaidusmanu** [comment]
Hello. The behavior of Google Drive is out of my control so I can't help you with that. You can try using rclone: https://rclone.org/drive/ or the Google Drive client to download everything at once.

**Comment by fantuslk** [comment]
Thank you so much for your  reply！

**Comment by fantuslk** [comment]
Hi mihaidusmanu,
I had another problem when I downloaded this file,the google drive keeps reporting errors in excess of the download quota.Could  you increase the download quota?Thank you.

**Comment by fantuslk** [comment]
When I use the google dirve client,it reported the same error.Please help to modify the download quota.

**Comment by mihaidusmanu** [comment]
If a significant number of people are downloading the same files at the same time, then Google blocks the downloads for a certain period of time to avoid abuse. The quota is reset every 24 hours as far as I know.
