### ISSUE TITLE
HPatches evaluation tool

### ISSUE THREAD

**Issue by vimalthilak** [mihaidusmanu/d2-net#4]
@mihaidusmanu Very nice work. Thanks for sharing your implementation!
Would it be possible for you to include an implementation for HPatches evaluation in this repo?

Thanks,

-Vimal

**Comment by mihaidusmanu** [comment]
Hello. Thank you! I will clean up the benchmark code and release it as part of this repository next week (Tuesday / Wednesday probably). I'll leave this issue open in the meantime.

**Comment by mihaidusmanu** [comment]
I just added the benchmark code to the repository! Let me know if you run into any issues.
