### ISSUE TITLE
the positive distance is consistent with the paper L2 distance

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#42]
Hi mihaidusmanu，
In the paper，the p(c)=||dA-dB||2.In the code,loss.py 86 line,
positive_distance = 2 - 2 * (
            descriptors1.t().unsqueeze(1) @ descriptors2.t().unsqueeze(2)
        ).squeeze().
They are not equal.

**Comment by mihaidusmanu** [comment]
I am not sure I understand what you mean. The descriptors are L2 normalized on lines 54 and 57 respectively, so the squared L2 distance can be formulated as in the code.

**Comment by fantuslk** [comment]
Thank you for your reply.I know.
