### ISSUE TITLE
Bug in HPatches evaluation notebook

### ISSUE THREAD

**Issue by vimalthilak** [mihaidusmanu/d2-net#5]
@mihaidusmanu : thanks for the notebook to reproduce results from your paper. It seems like the names of DELF and "hesaffnet" got switched in your plot?

> methods = ['hesaff', 'hesaffnet', 'delf', 'superpoint', 'lf-net', 'd2-net', 'd2-net-ms', 'd2-net-trained', 'd2-net-trained-ms']
> names = ['Hes. Aff. + Root-SIFT', 'DELF', 'HAN + HN++', 'SuperPoint', 'LF-Net', 'D2-Net', 'D2-Net MS', 'D2-Net Trained', 'D2-Net Trained MS']

Could you please fix that in your notebook when you get a chance? Thanks

**Comment by mihaidusmanu** [comment]
Good catch! Fixed. The results from the paper are in the correct order. It was a mix-up when cleaning the notebook.
