### ISSUE TITLE
trained model src

### ISSUE THREAD

**Issue by linqingfan** [mihaidusmanu/d2-net#50]
Hi,
Thanks for the excellent work!
I m having trouble finding how you trained the following:
models/d2_ots.pth
models/d2_tf.pth
Pardon me if I have missed the info in the paper or the github details
regards
QF

**Comment by uzpaka** [comment]
'_ots' means off-the-shelf (VGG-16 network pre-trained on ImageNet, without fine-tuning). For the '_tf' model, the last VGG-16 layer is fine-tuned.

**Comment by linqingfan** [comment]
Thanks for the info. Now I understand is all training on Megadepth dataset
