### ISSUE TITLE
InLoc dataset

### ISSUE THREAD

**Issue by bareblackfoot** [mihaidusmanu/d2-net#52]
How can I evaluate your code with InLoc dataset? (visual localization)

**Comment by mihaidusmanu** [comment]
Details regarding the InLoc evaluation are available in the ```inloc``` directory at: https://github.com/mihaidusmanu/d2-net/tree/master/inloc. In case you already tried that and ran into issues, please let me know.

**Comment by bareblackfoot** [comment]
Thanks a lot! I followed the instruction.
But I am stuck in converting results to txt format file (imglist2text.m)
Would you let me know is the right input of that function? 

The code needs a 'queryname' and 'P', but I think the output of your algorithm provides only keypoints, descriptors, and scores.

**Comment by bareblackfoot** [comment]
> Details regarding the InLoc evaluation are available in the `inloc` directory at: https://github.com/mihaidusmanu/d2-net/tree/master/inloc. In case you already tried that and ran into issues, please let me know.

Thanks a lot! I followed the instruction.
But I am stuck in converting results to txt format file (imglist2text.m)
Would you let me know what is the right input of that function? 

The code needs a 'queryname' and 'P', but I think the output of your algorithm provides only keypoints, descriptors, and scores.

**Comment by mihaidusmanu** [comment]
As mentioned in the readme, in order to get the poses, you will need to run `custom_demo` which will use the InLoc evaluation pipeline with D2-Net features (instead of SIFT / Dense). Upon completion of this step, you will find a `.mat` file with poses that can be fed to`imglist2text`.

**Comment by bareblackfoot** [comment]
Oh, I got it. Thank you a lot again :)
