### ISSUE TITLE
Training Time Inquiry

### ISSUE THREAD

**Issue by SwagJ** [mihaidusmanu/d2-net#56]
@mihaidusmanu 

Thank you for this great work. I just have one question about training time. How much time will it cost for training one batch?

**Comment by mihaidusmanu** [comment]
Hello! I haven't trained the network recently so I am not 100% sure. From what I recall, it used to take around 30 minutes per epoch on a 1080Ti (so around 5 hours for the 10 epochs in the training script).

**Comment by SwagJ** [comment]
Thank you for your reply. I am currently working on adaptation of D2NET on point clouds for my semester project with CVG. And on point cloud. The soft detection part forwarding is pretty slow. So I was wondering if this is normal. And now, I am pretty sure this is unnormal. Thank you very much for your information though.

**Comment by SwagJ** [comment]
Hi, @mihaidusmanu 

I just have one question about detection. When export the key point position, did you used Harris Corner detector in combination with local max and depth max to get detection on keypoint?

**Comment by mihaidusmanu** [comment]
Hello. As mentioned in the paper, we use the detection protocol from SIFT on the deep feature maps (which includes some edge-ness thresholding, not Harris exactly). This step only filters a very low number of keypoints in our case, but we kept it for completeness. Code for this step can be found in the HardDetectionModule.

https://github.com/mihaidusmanu/d2-net/blob/2a4d88fbe84961a3a17c46adb6d16a94b87020c5/lib/model_test.py#L81
