### ISSUE TITLE
About training another dataset

### ISSUE THREAD

**Issue by Jo-won** [mihaidusmanu/d2-net#58]
Thank you for good paper and code.
I will use this model in another datasets.
About that, i wonder whether i should re-train about another datasets or just use checkpoint about mega-depth in this case.
So could you tell me whether to re-train or not, when you evaluate in InLoc and Aachen Day-Night dataset?

**Comment by mihaidusmanu** [comment]
For all our experiments we trained only on MegaDepth and then used those weights to evaluate on HPatches Sequences / InLoc / Aachen / etc. No retraing was done.

**Comment by Jo-won** [comment]
Thank you for your answer!
