### ISSUE TITLE
request the experiment code

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#63]
Hi mihaidusmanu,could you please give me the code of the experiment in the paper, such as 5.1 image matching, 5.2 3d reconstruction, 5.3localization under chanllenging conditions.I found it difficult to implement the code by myself.Thank you!

**Comment by mihaidusmanu** [comment]
The code is already available online:
- Image matching: https://github.com/mihaidusmanu/d2-net/tree/master/hpatches_sequences
- 3D reconstruction: https://github.com/ahojnnes/local-feature-evaluation
- Aachen Day-Night: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation
- InLoc: https://github.com/mihaidusmanu/d2-net/tree/master/inloc

**Comment by fantuslk** [comment]
Thank you very much.

**Comment by fantuslk** [comment]
hi，@mihaidusmanu,in the Aachen Daynight's code,only get the result of (0.5m,2),(1m,5),(5m,10),how can I get the result of the features and (10m,25) in the paper?
Correctly localized queries (%)
Method                # Features 0.5m, 2◦ 1.0m, 5◦ 5.0m, 10◦ 10m, 25◦
Upright RootSIFT [29] 11.3K 36.7 54.1 72.5 81.6...

**Comment by mihaidusmanu** [comment]
Yes, only results for ((0.5m, 2), (1m, 5), (5m, 10)) are currently available to the evaluation system. You might want to contact the authors of the long-term visual localization benchmark for plots or results under different threshold. You can also try to open an issue at https://github.com/tsattler/visuallocalizationbenchmark.
