### ISSUE TITLE
What is `bbox` field return by dataset class

### ISSUE THREAD

**Issue by UditSinghParihar** [mihaidusmanu/d2-net#64]
Hello Sir,
    I have been trying to fine-tune D2Net on custom datasets, and from [issue 60](https://github.com/mihaidusmanu/d2-net/issues/60), it seems that we need to return exactly the same dictionary. 
I have RGB, depth, pose, and intrinsic information of the robot. But I don't how to give `bbox` field. Could you tell me how to generate `bbox` from the above information?

**Comment by mihaidusmanu** [comment]
Hello. We are using random 256x256 crops for training so the bbox are the coordinates of the top-left corner of the crop. If you are using full-resolution images then you can simply set this to 0, 0.
