### ISSUE TITLE
HardDetectionModule and HandcraftedLocalizationModule

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#65]
Hi @mihaidusmanu ,when I run the test set,I can't understand what these two functions do.Please help me.Thank  you.

**Comment by mihaidusmanu** [comment]
Hello. At test time, we use hard non-max-suppression (HardDetectionModule) which is not differentiable - see section 3.2 paragraph Hard Feature Detection for more details. We also use order two curve fitting nearby local maxima (HandcraftedLocalizationModule) to improve the positions of keypoints similar to SIFT (see Section 4.3 paragraph Test in the paper for a reference).
