### ISSUE TITLE
Invalid Models Links

### ISSUE THREAD

**Issue by engraamirkhan** [mihaidusmanu/d2-net#7]
Hi, 

The links for the models appear to be invalid.
Could you confirm this please?

Thank you.

**Comment by mihaidusmanu** [comment]
Hello,

All 3 links work fine on my end (both on my mobile connection and work one). The issue might be on your end. Does the project webpage -  https://dsmn.ml/publications/d2-net.html - work for you?

Mihai

**Comment by engraamirkhan** [comment]
Hi,

Thank you for checking this and I confirm, It is working now, all the links. 

Thank you so much.

**Comment by mihaidusmanu** [comment]
Thank you for the update. Let me know if you run into any other issue!

**Comment by engraamirkhan** [comment]
Thank you and I will.

Best regards,
aamir
