### ISSUE TITLE
The custom_demo runs very slowly

### ISSUE THREAD

**Issue by yuhf19** [mihaidusmanu/d2-net#70]
Hello Sir,
  I am trying to validate the data with the inloc evaluation, but it’s very inefficient when we run the custom_demo on MATLAB. Only 40 images were verified over the course of a day. What do you think are the reasons for this situation? What solutions would you suggest?
  Looking forward to your reply. Thank you very much.

**Comment by mihaidusmanu** [comment]
Hello. Did you try running the sparse_demo first? That one should be faster. How many workers are you using? I remember with 8-16 workers it would take maybe 1-2 days in total.

**Comment by yuhf19** [comment]
The sparse_demo runs as slowly as the custom_demo. In addition, only 6 workers on local. What's the problem?

**Comment by mihaidusmanu** [comment]
If it's the same for the sparse_demo, you should open an issue on the original InLoc demo repository. I did not contribute to the code so I cannot really help.
