### ISSUE TITLE
The results of Superpoint

### ISSUE THREAD

**Issue by pixelsmaker** [mihaidusmanu/d2-net#76]
Did you get the superpoint.npy in cache by using Superpoint-officially-pretrained model to extract features on the original image resolution, not 240*320 or 480*640 resolution?  Or you retrain the Superpoint model ?

**Comment by mihaidusmanu** [comment]
We use the official pretrained model on full resolution similar to other works (e.g., SuperGlue). All other parameters are the same as in the official repository.
