### ISSUE TITLE
I encounter a problem when I run on the Fountain,Herzjesu,southbuilding dataset use d2_pth.tf model

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#77]
![a1](https://user-images.githubusercontent.com/44725521/99808047-4562b280-2b7b-11eb-8b7f-281a342b412f.png)
![a2](https://user-images.githubusercontent.com/44725521/99808080-51e70b00-2b7b-11eb-926e-ff5a2c54291b.png)
the result of Fountain is normal
butbut thethe result of the Herzjesu and southbuilding's  dense points is too small...
Please  give me some advice.

**Comment by mihaidusmanu** [comment]
This is strange. Can you please post an image of the sparse model as returned by colmap? I suspect the poses are somehow wrong. I haven't evaluted D2 recently on these datasets so I am not sure where the issue might be coming from.

Also did you try other methods, e.g. SIFT, to make sure the data for these scenes is not corrupted?

**Comment by fantuslk** [comment]
Hi mihaidusmanu，
Thank you for your reply. Can you give ,me the results of three datasets run on D2-Net? I can't reproduce them for the moment.

**Comment by fantuslk** [comment]
![d2fcon1111](https://user-images.githubusercontent.com/44725521/99879279-d05caf00-2c46-11eb-9d92-96fc8ec386e3.PNG)
the sparse model result of foutain.
![d2hecon](https://user-images.githubusercontent.com/44725521/99879291-ecf8e700-2c46-11eb-9697-bac73305e449.png)
the sparse model result of herzjesu.
I can't tell the difference between them.

**Comment by fantuslk** [comment]
Hi mihaidusmanu，
I sorry.I found my mistake. I forgot to delete the previous reconstruction results, resulting in the dense reconstruction results that remain unchanged. Now other results are normal, that is, there is still a big difference between the mean track length and other methods.The paper uses the mean track length value as the track length or other values?
![d2herzjesu](https://user-images.githubusercontent.com/44725521/99882832-34d73880-2c5e-11eb-8b7d-3c8aa0f35d28.PNG)

**Comment by mihaidusmanu** [comment]
Hello. A shorter track length is normal. D2-Net has a lot of features (sometimes clustered together) and that ends up splitting longer tracks into multiple shorter ones. The following paper also reports similar results: https://arxiv.org/pdf/2003.08348.pdf
