### ISSUE TITLE
why need this transformation in the extract_feature.py 

### ISSUE THREAD

**Issue by fantuslk** [mihaidusmanu/d2-net#80]
Hi mihaidusmanu,
![捕获](https://user-images.githubusercontent.com/44725521/100908277-4ba34800-3506-11eb-95dc-7dff1e5afa6b.PNG)
why  i,j to u,v?

**Comment by mihaidusmanu** [comment]
We output keypoints in COLMAP format which is `x, y` with `x` pointing to the right and `y` pointing down. Please refer to the readme for more details https://github.com/mihaidusmanu/d2-net#feature-extraction. Depending on your specific application, you might want to use a different ordering.
