### ISSUE TITLE
missing scene_info-file in your google drive folder

### ISSUE THREAD

**Issue by Hai-Yen** [mihaidusmanu/d2-net#83]
Hello,
I have just noticed that your train_scenes.txt has a number of a scene, which has not the corresponding scene_info-file in your google drive folder (no .npz-file with the same number). 
It was the scene number 0092 and I don't know if there are other cases as well.

I only wanted to inform you about this.

**Comment by mihaidusmanu** [comment]
Hey. Thanks for letting me know. I just checked and scene 0092 doesn't have a sparse COLMAP model "0" in the original MegaDepth dataset. Thus, it's normal that the scene_info file is missing. I have removed it from the list of scenes in the master branch.
