### ISSUE TITLE
Does the model_test need to train once again?

### ISSUE THREAD

**Issue by xiezhiqing0112** [mihaidusmanu/d2-net#86]
Hello.the paper seems to use diffirent model in train and test.So what's the use of train model?I can't be loaded during infertime?

**Comment by 07Agarg** [comment]
Same doubt! @xiezhiqing0112, were you able to resolve this?

**Comment by mihaidusmanu** [comment]
The train model can be loaded during inference as both test and train have exactly the same layers / weights. The only changes between the two of them is that the test model uses different strides / dilation rates for the last layers which does not affect the trainable weights. This allows us to have a more light-weight training in terms of both memory usage and compute.

**Comment by 07Agarg** [comment]
Thanks for your quick response, @mihaidusmanu !
