### ISSUE TITLE
Failed to download models

### ISSUE THREAD

**Issue by farhadinima75** [mihaidusmanu/d2-net#91]
Trying `wget https://dsmn.ml/files/d2-net/d2_ots.pth` but getting this error:
```
--2022-03-15 18:56:45--  https://dsmn.ml/files/d2-net/d2_ots.pth                                                                                                         Resolving dsmn.ml (dsmn.ml)... 142.132.238.25
Connecting to dsmn.ml (dsmn.ml)|142.132.238.25|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-15 18:56:47 ERROR 404: Not Found.       
```
I think the server is down.

**Comment by mihaidusmanu** [comment]
I was migrating my server to a different cloud provider. Everything should be back to normal now.

Best,
Mihai.

**Comment by farhadinima75** [comment]
Thanks for your response.
But still, I can't download the model. Same error.

**Comment by mihaidusmanu** [comment]
Should be working now! Sorry about that.

**Comment by farhadinima75** [comment]
Yeah. Thanks.

**Comment by xiaoyugit111** [comment]
hey i meet the same problem.i couldn't download "d2_tf.pth"
have you solved this issue? please please help me with that.
my email : 22210720299@m.fudan.edu.cn

**Comment by xiaoyugit111** [comment]
problem solved. have a good day~
