### ISSUE TITLE
undistorted reconstructions dataset link Error 404

### ISSUE THREAD

**Issue by youngyyp** [mihaidusmanu/d2-net#93]
![image](https://user-images.githubusercontent.com/38950460/184055398-763cfea6-efd0-4dac-a47c-4e43ebd33fde.png)

**Comment by mihaidusmanu** [comment]
Hello. Sadly, the licensing of MegaDepth images is unclear so we cannot re-host the undistorted images. Please download the original images from the official website and preprocess the data as mentioned in the readme.

**Comment by leon5678** [comment]
> ![image](https://user-images.githubusercontent.com/38950460/184055398-763cfea6-efd0-4dac-a47c-4e43ebd33fde.png)

hi, did you get the pre-processed datasets or download the MegaDepth_SfM_v1.tar.xz successfully?
