### ISSUE TITLE
Inquiry about D2Net for Brain Tumor Segmentation on BraTS2018 Dataset 

### ISSUE THREAD

**Issue by MaggieLSY** [mihaidusmanu/d2-net#99]
Hi, I am currently working on applying missing modality models for brain tumor segmentation, and I have some questions regarding your experiments on the BraTS2018 dataset. I hope you don't mind sharing some details with me.

1. Having carefully studied the U2NET paper, I found the section on the three-fold data partitioning particularly intriguing. To further explore this aspect, I kindly request if you could **provide me with the list that outlines the specific division of data into three folds**. This information would greatly enhance my understanding of the experimental setup and facilitate my own research.

2. While reading the paper, I noticed that the authors mentioned the use of three-fold cross-validation. However, the reported results consist of a single value rather than the more conventional form of mean and standard deviation. I am curious to know **how the performance metric was calculated** and whether it represents an average value across the three folds.

Your valuable insights into these inquiries would be immensely helpful to me. I greatly appreciate your time and effort in addressing my questions. Thank you in advance for your kind assistance.

Looking forward to your response.

**Comment by mihaidusmanu** [comment]
It sounds like you are confusing D2-Net (this repository) with U2NET (not
sure what that is).

D2-Net is not used for Brain Tumour Segmentation but for local feature
matching.
